/**
 ******************************************************************************
 *
 * @file       sailmodthread.c
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Example module to be used as a template for actual modules.
 *             Threaded version.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

/**
 * Input objects: ExampleObject1, ExampleSettings
 * Output object: ExampleObject2
 *
 * This module executes in response to ExampleObject1 updates. When the
 * module is triggered it will update the data of ExampleObject2.
 *
 * The module executes in its own thread in this example.
 *
 * UAVObjects are automatically generated by the UAVObjectGenerator from
 * the object definition XML file.
 *
 * Modules have no API, all communication to other modules is done through UAVObjects.
 * However modules may use the API exposed by shared libraries.
 * See the OpenPilot wiki for more details.
 * http://www.openpilot.org/OpenPilot_Application_Architecture
 */

#include "openpilot.h"
#include "sailmodthread.h"
#include "sail.h"
#include "sailsettings.h" // object the module will listen for updates (input)
#include "sailstatus.h" // object the module will update (output)
//include "exampleings.h" // object holding module settings (input)

// Private constants
#define MAX_QUEUE_SIZE 20
#define STACK_SIZE     configMINIMAL_STACK_SIZE
#define TASK_PRIORITY  (tskIDLE_PRIORITY + 1)

// Private types

// Private variables
static xQueueHandle queue;
static xTaskHandle taskHandle;

// Private functions
static void sailTask(void *parameters);

/**
 * Initialise the module, called on startup
 * \returns 0 on success or -1 if initialisation failed
 */
int32_t SailModThreadInitialize()
{
    queue = xQueueCreate(MAX_QUEUE_SIZE, sizeof(UAVObjEvent));
    SailSettingsConnectQueue(queue);
    xTaskCreate(sailTask, (const  char *)"SailThread", STACK_SIZE, NULL, TASK_PRIORITY, &taskHandle);
    return 0;
}

/**
 * Module thread, should not return.
 */
static void sailTask(__attribute__((unused)) void *parameters)
{
    UAVObjEvent ev;
    SailSettingsData settings;
    SailStatusData  data;
//    int32_t step;
    while (1) {
      while (xQueueReceive(queue, &ev, portMAX_DELAY) != pdTRUE) { ; }
      if (ev.obj == SailStatusHandle()) {
	SailSettingsGet(&settings);
	SailStatusGet(&data);
	if (settings.BoatType == SAILSETTINGS_BOATTYPE_JOLLE) {
	data.MainSailPosition=10;
	SailStatusSet(&data);
	}
	if (settings.BoatType == SAILSETTINGS_BOATTYPE_SLOOP) {
	data.MainSailPosition=20;
	SailStatusSet(&data);
	}
	
      }
    }
}
   
